Add Body Parsing Middleware reference
mezzio/mezzio-authentication-oauth2 pull request #40
Opened 2021-12-14 13:09 UTC by cvigorsICBF

Mention the requirement for Body Parsing Middleware when parsing application/json requests

|    Q          |   A
|-------------- | ------
| Documentation | yes
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description
When requesting an access token from the authentication server using JSON, the response from the server will always be  "error": "unsupported_grant_type" unless the body parsing middleware helper is included in the application. Updating the docs to highlight the requirement for this library. Issue: https://github.com/mezzio/mezzio-authentication-oauth2/issues/39

2021-12-20 11:30 UTC, froschdesign requested changes

2021-12-20 11:30 UTC, froschdesign commented on docs/book/v1/authorization-server.md
> +
The current page contains the following steps:

* [Add the token endpoint](https://docs.mezzio.dev/mezzio-authentication-oauth2/v1/authorization-server/#add-the-token-endpoint)
* [Add the authorization endpoint](https://docs.mezzio.dev/mezzio-authentication-oauth2/v1/authorization-server/#add-the-authorization-endpoint)

And if the body parsing middleware is needed here, it should be added as a separate step under its own heading.

2022-01-05 17:37 UTC, cvigorsICBF commented
Header added as requested

2022-01-05 18:57 UTC, froschdesign requested changes, later dismissed

2022-01-05 18:57 UTC, froschdesign commented on docs/book/v1/authorization-server.md
> +To enable the token endpoint to handle the POST requests in JSON, the [Body Parsing Middleware](https://docs.mezzio.dev/mezzio/v3/features/helpers/body-parse/) helper should be included in the applic
```suggestion
## Add Body Parsing Middleware

To enable the token endpoint to handle the POST requests in JSON, the [Body Parsing Middleware](https://docs.mezzio.dev/mezzio/v3/features/helpers/body-parse/) helper should be included in the application. 
```

2022-01-05 18:57 UTC, froschdesign commented on docs/book/v1/authorization-server.md
> +To enable the token endpoint to handle the POST requests in JSON, the [Body Parsing Middleware](https://docs.mezzio.dev/mezzio/v3/features/helpers/body-parse/) helper should be included in the applic
If the middleware is required for the entire process then use "must" instead of "should":

> …helper **MUST** be included in the application.

2022-01-05 18:57 UTC, froschdesign commented on docs/book/v1/authorization-server.md
> +## Parsing JSON payloads in the token endpoint
Please add also a code example here. Thanks!

2022-01-31 10:43 UTC, cvigorsICBF reviewed
Example provided as requested

2022-03-30 20:14 UTC, weierophinney requested changes

2022-03-30 20:14 UTC, weierophinney commented on docs/book/v1/authorization-server.md
> +$app->pipe(BodyParamsMiddleware::class);
Generally speaking, we recommend AGAINST piping the body parsing middleware as generic middleware; instead, we recommend piping it into a route-specific pipeline:

```php
use Mezzio\Authentication\OAuth2;
use Mezzio\Helper\BodyParams\BodyParamsMiddleware;

$app->post('/oauth2/token', [
    BodyParamsMiddleware::class,
    OAuth2\TokenEndpointHandler::class
], 'auth.token');
```

This ensures we only parse it when we are actually expecting a content body.

2022-03-30 20:14 UTC, weierophinney commented on docs/book/v1/authorization-server.md
> +
This should be reverted; it adds an extra line between content, which our own linter will reject.

2022-06-13 12:37 UTC, froschdesign commented on docs/book/v1/authorization-server.md
> +This ensures we only parse it when we are actually expecting a content body.
The correct way of usage must be shown, not the wrong one.

``````suggestion
For example:

```php
use Mezzio\Authentication\OAuth2;
use Mezzio\Helper\BodyParams\BodyParamsMiddleware;

$app->post('/oauth2/token', [
    BodyParamsMiddleware::class,
    OAuth2\TokenEndpointHandler::class
], 'auth.token');
```

WARNING: Do not piping the body parsing middleware as generic middleware.
This ensures that the content body is only parsed when it is actually expected.
``````

2024-08-07 15:55 UTC, weierophinney approved these changes

2024-08-07 15:57 UTC, merged