update sql queries to support strings.
mezzio/mezzio-authentication-oauth2 pull request #80
Opened 2024-12-31 20:33 UTC by matthewpallotta

Update SQLite3 oauth2.sql to use VARCHAR and not INT for oauth_access_tokens and oauth_auth_codes for user_id and client_id. 
Add MySQL version with VARCAHAR.

|    Q          |   A
|-------------- | ------
| Documentation | yes/no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description
In the SQLite SQL file, the tables oauth_access_tokens and oauth_auth_codes have columns user_id and client_id set to INT. The code enters strings into those columns. The unit tests for Test/Pdo/OAuth2PdoMiddlewareTest.php will pass as the SQLite Schema does not specify STRICT MODE for INT. This allows strings to be entered into the columns. [https://www.sqlite.org/stricttables.html](url). 

#### Before
`sqlite> select * from oauth_auth_codes;`
`1dc8adb4e0dba6efeaff8c17362bdd5f0c92bcf3e7578998d468d7398253eb338c438f3e3fa3103c|test|client_test2|test|1|2024-12-31 19:05:07`
`sqlite> PRAGMA table_info(oauth_auth_codes);`
`0|id|varchar(100)|1||1
1|user_id|int(10)|0|NULL|0
2|client_id|int(10)|1||0
3|scopes|TEXT|0||0
4|revoked|tinyint(1)|1|'0'|0
5|expires_at|datetime|0|NULL|0`

#### After
`sqlite> select * from oauth_auth_codes;`
`d289774593942f5de1967783eee521197c968fcc2efa9e248ce1e9c008af222d945af2b13bd00c89|test|client_test2|test|1|2024-12-31 19:53:06`
`sqlite> PRAGMA table_info(oauth_auth_codes);`
`0|id|varchar(100)|1||1
1|user_id|varchar(320)|0|NULL|0
2|client_id|varchar(100)|1||0
3|scopes|TEXT|0||0
4|revoked|tinyint(1)|1|'0'|0
5|expires_at|datetime|0|NULL|0
`

#### Note:
I included a MySQL version of the schema to make it easier for end-users on that platform.

2025-01-02 13:16 UTC, matthewpallotta commented
Added sign-off

2025-01-02 14:15 UTC, samsonasik commented
You need to use rebase instead of merge to have clean commits, so DCO will pass, I wrote a blog post about it 

https://samsonasik.wordpress.com/2015/09/16/practical-git-4-rebasing-conflicted-task-branch-against-primary-branch/

2025-01-05 01:57 UTC, matthewpallotta commented
Ok, I followed the notes on the DCO details. I will try yours.

2025-01-05 11:55 UTC, froschdesign requested changes

2025-01-05 11:55 UTC, froschdesign commented on .gitignore
> +.idea
Please revert this and use your global Git configuration to ignore this folder. Otherwise we have to list all IDE-specific folders here.

2025-01-05 11:55 UTC, froschdesign commented on data/oauth2.mysql.sql
> +CREATE TABLE `oauth_access_tokens` (
And what about PostgreSQL or should ANSI standard SQL be used?

2025-01-05 11:55 UTC, froschdesign commented on data/oauth2.mysql.sql
> +CREATE INDEX `IDX_CA42527CA76ED39519EB6921BDA26CCD` ON oauth_access_tokens (`user_id`,`client_id`);
Can meaningful names not be used here?

2025-01-06 19:57 UTC, matthewpallotta commented
Is there a good way to delete this PR, and I'll move on and forget about this?

2025-01-06 19:59 UTC, closed without merging

2025-01-06 19:59 UTC, matthewpallotta commented
Closing it.